{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: prometheus
        isDefault: true
        url: http://prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090

      - name: Loki
        type: loki
        uid: loki
        url: http://loki.{{ .Release.Namespace }}.svc.cluster.local:3100
{{- end }}
