{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.adminPasswordExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-es
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-team5

  target:
    name: grafana-admin
    creationPolicy: Owner

  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.monitoring.grafana.externalSecretPath }}
        property: {{ .Values.monitoring.grafana.externalSecretProperty }}
{{- end }}
