apiVersion: v2
name: team5-app
description: A Helm chart for the team5-app
type: application

version: 0.1.0

appVersion: "1.0.0"
dependencies:
  - name: kafka
    version: 26.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
    