apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: notification-service-kafka-auth
spec:
  secretTargetRef:
    - parameter: saslUsername
      name: team5-secret
      key: notification-user
    - parameter: saslPassword
      name: team5-secret
      key: KAFKA_NOTIFICATION_PASSWORD