apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  labels:
    app: notification-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
