apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: quay.io/cloudhut/kafka-exporter:v1.7.0
          args:
            - --kafka.seed-brokers={{ .Values.kafka.bootstrapServers }}
            - --kafka.version=2.0.0
            - --log.level=info
            - --web.listen-address=:9308
            - --web.telemetry-path=/metrics
          ports:
            - containerPort: 9308
              name: metrics
          livenessProbe:
            httpGet:
              path: /health
              port: 9308
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 9308
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  type: ClusterIP
