apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV1
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: scram
        port: 9094
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
  entityOperator:
    topicOperator:
      bootstrapServers: {{ .Values.kafka.clusterName }}-kafka-bootstrap:9094
      resources:
        requests:
          cpu: {{ .Values.kafka.entityOperator.topicOperator.resources.requests.cpu }}
          memory: {{ .Values.kafka.entityOperator.topicOperator.resources.requests.memory }}
        limits:
          cpu: {{ .Values.kafka.entityOperator.topicOperator.resources.limits.cpu }}
          memory: {{ .Values.kafka.entityOperator.topicOperator.resources.limits.memory }}
    userOperator:
      bootstrapServers: {{ .Values.kafka.clusterName }}-kafka-bootstrap:9094
      resources:
        requests:
          cpu: {{ .Values.kafka.entityOperator.userOperator.resources.requests.cpu }}
          memory: {{ .Values.kafka.entityOperator.userOperator.resources.requests.memory }}
        limits:
          cpu: {{ .Values.kafka.entityOperator.userOperator.resources.limits.cpu }}
          memory: {{ .Values.kafka.entityOperator.userOperator.resources.limits.memory }}

---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaNodePool
# metadata:
#   name: broker
#   namespace: {{ .Release.Namespace }}
#   labels:
#     strimzi.io/cluster: {{ .Values.kafka.clusterName }}
# spec:
#   replicas: {{ .Values.kafka.replicas }}
#   roles:
#     - broker
#     - controller
#   storage:
#     type: ephemeral
#   resources:
#     requests:
#       cpu: {{ .Values.kafka.resources.requests.cpu }}
#       memory: {{ .Values.kafka.resources.requests.memory }}
#     limits:
#       cpu: {{ .Values.kafka.resources.limits.cpu }}
#       memory: {{ .Values.kafka.resources.limits.memory }}
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 2
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
  resources:
    requests:
      cpu: {{ .Values.kafka.resources.requests.cpu }}
      memory: {{ .Values.kafka.resources.requests.memory }}
    limits:
      cpu: {{ .Values.kafka.resources.limits.cpu }}
      memory: {{ .Values.kafka.resources.limits.memory }}
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
  resources:
    requests:
      cpu: {{ .Values.kafka.resources.requests.cpu }}
      memory: {{ .Values.kafka.resources.requests.memory }}
    limits:
      cpu: {{ .Values.kafka.resources.limits.cpu }}
      memory: {{ .Values.kafka.resources.limits.memory }}
