# [jg:person_17] нод для роли 'controller'
apiVersion: kafka.strimzi.io/v1beta2 # <-- ПРАВИЛЬНАЯ ВЕРСИЯ API
kind: KafkaNodePool
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral # <-- ВАШ ВАРИАНТ ХРАНИЛИЩА
  resources:
    requests:
      cpu: {{ .Values.kafka.resources.requests.cpu }}
      memory: {{ .Values.kafka.resources.requests.memory }}
    limits:
      cpu: {{ .Values.kafka.resources.limits.cpu }}
      memory: {{ .Values.kafka.resources.limits.memory }}
---

# Пул нод для роли 'broker'
apiVersion: kafka.strimzi.io/v1beta2 # <-- ПРАВИЛЬНАЯ ВЕРСИЯ API
kind: KafkaNodePool
metadata:
  name: broker
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral # <-- ВАШ ВАРИАНТ ХРАНИЛИЩА
  resources:
    requests:
      cpu: {{ .Values.kafka.resources.requests.cpu }}
      memory: {{ .Values.kafka.resources.requests.memory }}
    limits:
      cpu: {{ .Values.kafka.resources.limits.cpu }}
      memory: {{ .Values.kafka.resources.limits.memory }}
---

# Основной ресурс Kafka
apiVersion: kafka.strimzi.io/v1beta2 # <-- ПРАВИЛЬНАЯ ВЕРСИЯ API
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  kafka:
    version: 3.7.0 # <-- РЕАЛЬНАЯ ВЕРСИЯ KAFKA
    authorization:
      type: simple
    listeners:
      - name: kraft # Уникальное имя для KRaft
        port: 9091
        type: internal
        tls: true
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
  entityOperator:
    topicOperator: {}
    userOperator: {}
