apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: producer-service-pdb
  labels:
    app: producer-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: producer-service
