{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.adminPasswordExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-es
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: grafana-admin
    creationPolicy: Owner

  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.monitoring.grafana.externalSecretPath }}
        property: {{ .Values.monitoring.grafana.externalSecretProperty }}
{{- end }}
