apiVersion: v1
kind: Service
metadata:
  name: {{ include "team5-app.fullname" . }}-kafka-svc # Имя сервиса: <имя-релиза>-kafka-svc
  labels:
    {{- include "team5-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: {{ include "team5-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka
