{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
{{- end }}
